# Exported from Render on 2026-04-27T14:45:36Z
version: 1
services:
- type: web
  name: crosschain-yield-gas-oracle-1
  runtime: node
  repo: https://github.com/Elan41/crosschain-yield-gas-oracle
  plan: free
  envVars:
  - key: RECEIVING_WALLET
    sync: false
  region: oregon
  buildCommand: yarn install
  startCommand: node src/server.js
  autoDeployTrigger: commit
